name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hi there!\n\n🎉 Welcome to our GitHub repository! Thank you for opening your first issue. We appreciate your contribution to our project.\nOur team will look into the issue at the earliest. If you have any additional information or suggestions, feel free to share them. Your input is valuable to us.\n\nIf you have any questions or need assistance, don't hesitate to reach out. Happy coding!"
        pr-message: "Hi there!\n\n🚀 Congratulations on your first pull request! We're thrilled to see your contribution to our project.\nOur team will review your pull request at the earliest. If there are any changes or additional information needed, we'll provide feedback. Your effort is greatly appreciated.\n\nIf you have any questions or need guidance, feel free to ask. We're here to help and excited to collaborate with you."
